# -*- coding: utf-8 -*-
"""

 Copyright [2012] [Redacted Labs]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

-------
"""

import os
import shutil
from tornado.template import Loader

'''
This class is used to bootstrap a project and
cook all of the initial files
'''
class Chef():

	def __init__(self, project_name=None):
		self.project_name = project_name
		#This contains all of the folders that will be created in bootstrap
		self.folders = [
			'handlers', 'libs', 'models', 'setup', 
			'static', 'templates', 'test', 'files',
			# For now these directories are created in the copy process
			# os.path.join('static', 'css'),
			# os.path.join('static', 'js'),
			# os.path.join('static', 'images'),
		]
		#These are the templates that will be auto-generated by tornado's templating engine
		self.templates = [
			('main', '__main__.py'),
			('handlers', os.path.join('handlers','__init__.py')),
			('base_handler', os.path.join('handlers','BaseHandler.py')),
			('models', os.path.join('models','__init__.py')),
			('base_object', os.path.join('models','BaseObject.py')),
			('html_main', os.path.join('templates','main.html'))
		]

	def bootstrap(self):
		#Create parameterized files
		self.create_folders()
		self.create_files()
		self.copy_static_files()

	def project_sub_directory(self, directory_name):
		return os.path.join(os.getcwd(), self.project_name, directory_name)

	def copy_static_files(self):
		shutil.copytree(os.path.join('templates', 'static', 'css'), os.path.join(os.getcwd(), self.project_name, 'static', 'css'))
		shutil.copytree(os.path.join('templates', 'static', 'img'), os.path.join(os.getcwd(), self.project_name, 'static', 'img'))
		shutil.copytree(os.path.join('templates', 'static', 'js'), os.path.join(os.getcwd(), self.project_name, 'static', 'js'))
		print "[*] Finished copying static files to project", self.project_name

	def create_folders(self):
		for folder in self.folders:
			if not os.path.exists(self.project_sub_directory(folder)):
			    os.makedirs(self.project_sub_directory(folder))
		print '[*] Finished creating all project folders!'

	def create_files(self):
		self.loader = Loader(os.path.join(os.getcwd(),"templates"))
		
		for template, file_name in self.templates:
			temp_file = open(os.path.join(os.getcwd(), self.project_name, file_name), 'w')
			temp_file.write(self.loader.load(template+".plate").generate(project_name=self.project_name))
			temp_file.close()
			print "[*] Finished generating", template, "Template!" 

